name: GitHub Metrics

on:
  schedule:
    - cron: "0 * * * *"  
  workflow_dispatch:     

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: NikhilSharma-30
          template: classic
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          config_timezone: 'Asia/Kolkata'  
